// frontend/src/App.jsx
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { AuthProvider, useAuth } from './context/AuthContext';
import ProtectedRoute from './components/ProtectedRoute';
import Sidebar from './components/Sidebar';
import LoginPage from './pages/LoginPage';
import SignupPage from './pages/SignupPage';
import PatientDashboard from './pages/patient/PatientDashboard';
import ClinicianDashboard from './pages/clinician/ClinicianDashboard';
import AdminDashboard from './pages/admin/AdminDashboard';
import LoadingSpinner from './components/LoadingSpinner';

function DashboardRedirect() {
  const { user, loading } = useAuth();
  if (loading) return <div className="flex-center" style={{ height: '100vh' }}><LoadingSpinner /></div>;
  if (!user) return <Navigate to="/login" replace />;
  const routes = { PATIENT: '/patient', CLINICIAN: '/clinician', ADMIN: '/admin' };
  return <Navigate to={routes[user.role] || '/login'} replace />;
}

function AppLayout({ children }) {
  return (
    <div className="app-layout">
      <Sidebar />
      <main className="main-content">{children}</main>
    </div>
  );
}

function AppRoutes() {
  return (
    <Routes>
      <Route path="/login" element={<LoginPage />} />
      <Route path="/signup" element={<SignupPage />} />
      <Route path="/" element={<DashboardRedirect />} />
      <Route path="/dashboard" element={<DashboardRedirect />} />

      {/* Patient Routes */}
      <Route path="/patient" element={
        <ProtectedRoute allowedRoles={['PATIENT']}>
          <AppLayout><PatientDashboard /></AppLayout>
        </ProtectedRoute>
      } />
      <Route path="/patient/*" element={
        <ProtectedRoute allowedRoles={['PATIENT']}>
          <AppLayout><PatientDashboard /></AppLayout>
        </ProtectedRoute>
      } />

      {/* Clinician Routes */}
      <Route path="/clinician" element={
        <ProtectedRoute allowedRoles={['CLINICIAN']}>
          <AppLayout><ClinicianDashboard /></AppLayout>
        </ProtectedRoute>
      } />
      <Route path="/clinician/*" element={
        <ProtectedRoute allowedRoles={['CLINICIAN']}>
          <AppLayout><ClinicianDashboard /></AppLayout>
        </ProtectedRoute>
      } />

      {/* Admin Routes */}
      <Route path="/admin" element={
        <ProtectedRoute allowedRoles={['ADMIN']}>
          <AppLayout><AdminDashboard /></AppLayout>
        </ProtectedRoute>
      } />
      <Route path="/admin/*" element={
        <ProtectedRoute allowedRoles={['ADMIN']}>
          <AppLayout><AdminDashboard /></AppLayout>
        </ProtectedRoute>
      } />

      <Route path="*" element={<Navigate to="/" replace />} />
    </Routes>
  );
}

export default function App() {
  return (
    <BrowserRouter>
      <AuthProvider>
        <AppRoutes />
      </AuthProvider>
    </BrowserRouter>
  );
}

// frontend-svelte/src/App.svelte
<script>
  import Router from 'svelte-spa-router'
  import { replace } from 'svelte-spa-router'
  import { wrap } from 'svelte-spa-router/wrap'
  import { onMount } from 'svelte'
  import { session } from './lib/session.js'
  import LoginPage from './pages/LoginPage.svelte'
  import SignupPage from './pages/SignupPage.svelte'
  import PatientDashboard from './pages/PatientDashboard.svelte'
  import ClinicianDashboard from './pages/ClinicianDashboard.svelte'
  import AdminDashboard from './pages/AdminDashboard.svelte'
  import GuardedPage from './components/GuardedPage.svelte'
  import ToastContainer from './components/ToastContainer.svelte'
  import { notifications } from './lib/notifications.js'

  const roleRoutes = {
    PATIENT: '/patient',
    CLINICIAN: '/clinician',
    ADMIN: '/admin',
  }

  function redirectHome() {
    if ($session.loading) return
    replace($session.user ? roleRoutes[$session.user.role] || '/login' : '/login')
  }

  function guarded(component, roles) {
    return wrap({
      component: GuardedPage,
      props: { component, roles },
    })
  }

  const routes = {
    '/': redirectHome,
    '/login': LoginPage,
    '/signup': SignupPage,
    '/patient': guarded(PatientDashboard, ['PATIENT']),
    '/patient/*': guarded(PatientDashboard, ['PATIENT']),
    '/clinician': guarded(ClinicianDashboard, ['CLINICIAN']),
    '/clinician/*': guarded(ClinicianDashboard, ['CLINICIAN']),
    '/admin': guarded(AdminDashboard, ['ADMIN']),
    '/admin/*': guarded(AdminDashboard, ['ADMIN']),
    '*': redirectHome,
  }

  onMount(() => {
    session.restore()
    const token = localStorage.getItem('rpm_token')
    notifications.start(token)
    notifications.refresh()
    return () => notifications.stop()
  })
</script>

{#if $session.loading}
  <main class="screen-center">
    <div class="loader"></div>
  </main>
{:else}
  <Router {routes} />
{/if}

<ToastContainer />
