// frontend-svelte/src/pages/PatientDashboard.svelte
<script>
  import { onMount } from 'svelte'
  import { CalendarPlus, FileHeart, RefreshCw, Save } from 'lucide-svelte'
  import StatCard from '../components/StatCard.svelte'
  import RiskBadge from '../components/RiskBadge.svelte'
  import { assignmentsApi, cliniciansApi, followupAppointmentsApi, followupResponsesApi, patientsApi, reportsApi } from '../lib/api.js'
  import { session } from '../lib/session.js'
  import { toasts } from '../lib/toasts.js'

  const tabs = [
    { key: 'dashboard', href: '/patient', label: 'Dashboard' },
    { key: 'report', href: '/patient/report', label: 'Report Symptoms' },
    { key: 'clinicians', href: '/patient/clinicians', label: 'My Clinicians' },
    { key: 'history', href: '/patient/history', label: 'Report History' },
    { key: 'profile', href: '/patient/profile', label: 'Profile' },
  ]

  let activeTab = 'dashboard'
  let loading = true
  let submitting = false
  let savingProfile = false
  let error = ''

  let patient = null
  let reports = []
  let assignments = []
  let clinicians = []
  let followupResponses = []
  let appointments = []

  let reportForm = {
    symptomsText: '',
    severity: 'MILD',
    durationDays: 1,
    frequency: 'FIRST_TIME',
    notes: '',
    temperature: '',
    heartRate: '',
    medicationAdherent: '',
  }

  let profileForm = {
    dateOfBirth: '',
    gender: '',
    emergencyContact: '',
    address: '',
    chronicConditions: '',
    allergies: '',
    baselineStatus: 'stable',
  }

  $: latest = reports[0]
  $: activeAssignments = assignments.filter((item) => item.status === 'ACTIVE')
  $: canReport = Boolean(patient && activeAssignments.length > 0)

  function setTabFromHash() {
    const path = window.location.hash.replace(/^#/, '') || '/patient'
    const match = tabs.find((tab) => path === tab.href)
    activeTab = match?.key || 'dashboard'
  }

  async function load() {
    loading = true
    error = ''
    try {
      const [patientsRes, assignmentsRes, cliniciansRes] = await Promise.allSettled([
        patientsApi.list(),
        assignmentsApi.list(),
        cliniciansApi.list(),
      ])
      const patients = patientsRes.status === 'fulfilled' ? patientsRes.value : []
      const allAssignments = assignmentsRes.status === 'fulfilled' ? assignmentsRes.value : []
      const allClinicians = cliniciansRes.status === 'fulfilled' ? cliniciansRes.value : []

      patient = patients.find((item) => item.userId === $session.user.id)
      assignments = patient ? allAssignments.filter((item) => item.patientId === patient.id) : []
      clinicians = allClinicians

      if (patient) {
        const [reportsRes, responsesRes, appointmentsRes] = await Promise.allSettled([
          reportsApi.byPatient(patient.id),
          followupResponsesApi.listForPatient(patient.id),
          followupAppointmentsApi.list({ patientId: patient.id }),
        ])
        reports = reportsRes.status === 'fulfilled' ? reportsRes.value || [] : []
        followupResponses = responsesRes.status === 'fulfilled' ? responsesRes.value || [] : []
        appointments = appointmentsRes.status === 'fulfilled' ? appointmentsRes.value || [] : []

        profileForm = {
          dateOfBirth: patient.dateOfBirth ? new Date(patient.dateOfBirth).toISOString().split('T')[0] : '',
          gender: patient.gender || '',
          emergencyContact: patient.emergencyContact || '',
          address: patient.address || '',
          chronicConditions: parseJsonArray(patient.chronicConditions).join(', '),
          allergies: parseJsonArray(patient.allergies).join(', '),
          baselineStatus: patient.baselineStatus || 'stable',
        }
      } else {
        reports = []
        followupResponses = []
        appointments = []
      }
    } catch (err) {
      error = err.message || 'Failed to load patient data'
    } finally {
      loading = false
    }
  }

  function parseJsonArray(value) {
    if (!value) return []
    if (Array.isArray(value)) return value
    try {
      const parsed = JSON.parse(value)
      return Array.isArray(parsed) ? parsed : []
    } catch {
      return []
    }
  }

  async function submitReport() {
    if (!patient || !reportForm.symptomsText.trim()) {
      toasts.warning('Please add at least one symptom')
      return
    }

    submitting = true
    try {
      await reportsApi.create({
        patientId: patient.id,
        symptoms: reportForm.symptomsText.split(',').map((item) => item.trim()).filter(Boolean),
        severity: reportForm.severity,
        durationDays: Number(reportForm.durationDays),
        frequency: reportForm.frequency,
        notes: reportForm.notes || null,
        temperature: reportForm.temperature ? Number(reportForm.temperature) : null,
        heartRate: reportForm.heartRate ? Number(reportForm.heartRate) : null,
        medicationAdherent: reportForm.medicationAdherent === '' ? null : reportForm.medicationAdherent === 'true',
      })
      reportForm = {
        symptomsText: '',
        severity: 'MILD',
        durationDays: 1,
        frequency: 'FIRST_TIME',
        notes: '',
        temperature: '',
        heartRate: '',
        medicationAdherent: '',
      }
      toasts.success('Symptom report submitted')
      await load()
      window.location.hash = '#/patient/history'
    } catch (err) {
      toasts.error(err.message || 'Failed to submit report')
    } finally {
      submitting = false
    }
  }

  async function saveProfile() {
    if (!patient) return
    savingProfile = true
    try {
      const payload = {
        dateOfBirth: profileForm.dateOfBirth || null,
        gender: profileForm.gender || null,
        emergencyContact: profileForm.emergencyContact || null,
        address: profileForm.address || null,
        chronicConditions: JSON.stringify(splitCommaList(profileForm.chronicConditions)),
        allergies: JSON.stringify(splitCommaList(profileForm.allergies)),
        baselineStatus: profileForm.baselineStatus || 'stable',
      }
      await patientsApi.update(patient.id, payload)
      toasts.success('Profile updated')
      await load()
    } catch (err) {
      toasts.error(err.message || 'Failed to update profile')
    } finally {
      savingProfile = false
    }
  }

  function splitCommaList(value) {
    return value
      .split(',')
      .map((item) => item.trim())
      .filter(Boolean)
  }

  function resolveClinicianName(clinicianId) {
    const clinician = clinicians.find((item) => item.id === clinicianId)
    return clinician?.user?.fullName || 'Assigned clinician'
  }

  onMount(() => {
    setTabFromHash()
    window.addEventListener('hashchange', setTabFromHash)
    load()
    return () => window.removeEventListener('hashchange', setTabFromHash)
  })
</script>

<header class="page-header">
  <div>
    <h1>Patient workspace</h1>
    <p>Report symptoms, track clinician follow-up, and keep your profile up to date.</p>
  </div>
  <button class="button secondary" type="button" on:click={load}><RefreshCw size={16} /> Refresh</button>
</header>

<nav class="tabs" aria-label="Patient tabs">
  {#each tabs as tab}
    <a href={`#${tab.href}`} class:active={activeTab === tab.key}>{tab.label}</a>
  {/each}
</nav>

{#if loading}
  <div class="loader"></div>
{:else if error}
  <div class="error">{error}</div>
{:else if activeTab === 'dashboard'}
  <div class="grid stats">
    <StatCard label="Reports submitted" value={reports.length} />
    <StatCard label="Active assignments" value={activeAssignments.length} />
    <StatCard label="Latest risk level" value={latest?.riskLevel || 'N/A'} />
    <StatCard label="Upcoming follow-ups" value={appointments.filter((item) => item.status === 'SCHEDULED').length} />
  </div>

  <div class="grid two-col" style="margin-top:16px;">
    <section class="card">
      <h2>Latest report</h2>
      {#if latest}
        <div class="row">
          <div class="row-title">
            <strong>{latest.symptoms?.join(', ') || 'Symptom report'}</strong>
            <span>{new Date(latest.createdAt).toLocaleString()}</span>
          </div>
          <RiskBadge value={latest.riskLevel} />
        </div>
      {:else}
        <div class="empty">No reports yet.</div>
      {/if}
    </section>

    <section class="card">
      <h2>Clinician responses</h2>
      <div class="list">
        {#each followupResponses.slice(0, 5) as response}
          <div class="row">
            <div class="row-title">
              <strong>{response.message || 'Follow-up response'}</strong>
              <span>{new Date(response.createdAt).toLocaleString()}</span>
            </div>
          </div>
        {:else}
          <div class="empty">No clinician responses yet.</div>
        {/each}
      </div>
    </section>
  </div>
{:else if activeTab === 'report'}
  <section class="card">
    <h2>Submit symptom report</h2>
    {#if !canReport}
      <div class="notice">You need at least one ACTIVE clinician assignment before you can submit symptoms.</div>
    {/if}
    <form class="form-grid" on:submit|preventDefault={submitReport}>
      <div class="field">
        <label>Symptoms</label>
        <input bind:value={reportForm.symptomsText} placeholder="e.g. fever, cough, chest_pain" disabled={!canReport || submitting} />
      </div>
      <div class="field">
        <label>Severity</label>
        <select bind:value={reportForm.severity} disabled={!canReport || submitting}>
          <option value="MILD">MILD</option>
          <option value="MODERATE">MODERATE</option>
          <option value="SEVERE">SEVERE</option>
        </select>
      </div>
      <div class="field">
        <label>Duration (days)</label>
        <input type="number" min="1" bind:value={reportForm.durationDays} disabled={!canReport || submitting} />
      </div>
      <div class="field">
        <label>Frequency</label>
        <select bind:value={reportForm.frequency} disabled={!canReport || submitting}>
          <option value="FIRST_TIME">FIRST_TIME</option>
          <option value="INTERMITTENT">INTERMITTENT</option>
          <option value="CONSTANT">CONSTANT</option>
          <option value="WORSENING">WORSENING</option>
        </select>
      </div>
      <div class="grid two-col">
        <div class="field">
          <label>Temperature (optional)</label>
          <input type="number" step="0.1" bind:value={reportForm.temperature} disabled={!canReport || submitting} />
        </div>
        <div class="field">
          <label>Heart rate (optional)</label>
          <input type="number" bind:value={reportForm.heartRate} disabled={!canReport || submitting} />
        </div>
      </div>
      <div class="field">
        <label>Medication adherence</label>
        <select bind:value={reportForm.medicationAdherent} disabled={!canReport || submitting}>
          <option value="">Not set</option>
          <option value="true">Adherent</option>
          <option value="false">Not adherent</option>
        </select>
      </div>
      <div class="field">
        <label>Notes</label>
        <textarea bind:value={reportForm.notes} disabled={!canReport || submitting}></textarea>
      </div>
      <button class="button primary" type="submit" disabled={!canReport || submitting}>
        {submitting ? 'Submitting...' : 'Submit report'}
      </button>
    </form>
  </section>
{:else if activeTab === 'clinicians'}
  <section class="card">
    <h2>My clinicians</h2>
    <div class="list">
      {#each activeAssignments as assignment}
        <div class="row">
          <div class="row-title">
            <strong>{assignment.clinician?.user?.fullName || resolveClinicianName(assignment.clinicianId)}</strong>
            <span>{assignment.careContext || 'GENERAL_REVIEW'}</span>
          </div>
          <span class="badge low">{assignment.status}</span>
        </div>
      {:else}
        <div class="empty">No active clinicians assigned.</div>
      {/each}
    </div>
  </section>
{:else if activeTab === 'history'}
  <section class="card">
    <h2>Report history</h2>
    <div class="list">
      {#each reports as report}
        <div class="row">
          <div class="row-title">
            <strong>{report.symptoms?.join(', ') || 'Symptom report'}</strong>
            <span>{new Date(report.createdAt).toLocaleString()}</span>
          </div>
          <RiskBadge value={report.riskLevel || 'LOW'} />
        </div>
      {:else}
        <div class="empty">No reports available.</div>
      {/each}
    </div>
  </section>
{:else if activeTab === 'profile'}
  <section class="card">
    <h2>Profile</h2>
    <form class="form-grid" on:submit|preventDefault={saveProfile}>
      <div class="grid two-col">
        <div class="field">
          <label>Date of birth</label>
          <input type="date" bind:value={profileForm.dateOfBirth} disabled={savingProfile} />
        </div>
        <div class="field">
          <label>Gender</label>
          <input bind:value={profileForm.gender} disabled={savingProfile} />
        </div>
      </div>
      <div class="field">
        <label>Emergency contact</label>
        <input bind:value={profileForm.emergencyContact} disabled={savingProfile} />
      </div>
      <div class="field">
        <label>Address</label>
        <textarea bind:value={profileForm.address} disabled={savingProfile}></textarea>
      </div>
      <div class="field">
        <label>Chronic conditions (comma separated)</label>
        <input bind:value={profileForm.chronicConditions} disabled={savingProfile} />
      </div>
      <div class="field">
        <label>Allergies (comma separated)</label>
        <input bind:value={profileForm.allergies} disabled={savingProfile} />
      </div>
      <div class="field">
        <label>Baseline status</label>
        <select bind:value={profileForm.baselineStatus} disabled={savingProfile}>
          <option value="stable">stable</option>
          <option value="improving">improving</option>
          <option value="worsening">worsening</option>
        </select>
      </div>
      <button class="button primary" type="submit" disabled={savingProfile}>
        <Save size={16} />
        {savingProfile ? 'Saving...' : 'Save profile'}
      </button>
    </form>
  </section>
{/if}

{#if activeTab === 'dashboard' || activeTab === 'history'}
  <section class="card" style="margin-top:16px;">
    <div class="toolbar">
      <h2>Appointments</h2>
      <CalendarPlus size={18} />
    </div>
    <div class="list">
      {#each appointments.slice(0, 8) as item}
        <div class="row">
          <div class="row-title">
            <strong>{new Date(item.scheduledAt).toLocaleString()}</strong>
            <span>{item.reason || 'Follow-up appointment'}</span>
          </div>
          <span class="badge moderate">{item.status || 'SCHEDULED'}</span>
        </div>
      {:else}
        <div class="empty">No appointments yet.</div>
      {/each}
    </div>
  </section>
{/if}

// frontend/src/pages/patient/PatientDashboard.jsx
import { useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { useToast } from '../../context/ToastContext';
import { useNotifications } from '../../context/NotificationContext';
import { symptomReportsAPI } from '../../api/symptomReports';
import { patientsAPI } from '../../api/patients';
import { assignmentsAPI } from '../../api/assignments';
import { usersAPI } from '../../api/users';
import TopBar from '../../components/TopBar';
import StatCard from '../../components/StatCard';
import RiskBadge from '../../components/RiskBadge';

import LoadingSpinner from '../../components/LoadingSpinner';
import {
  Heart, Activity, Shield, Stethoscope, FileHeart, Clock, Thermometer,
  HeartPulse, Pill, Send, Plus, ClipboardList, Calendar, AlertCircle,
  LayoutDashboard, UserCircle
} from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Area, AreaChart } from 'recharts';
import './PatientDashboard.css';

const COMMON_CONDITIONS = [
  'asthma', 'copd', 'diabetes', 'hypertension', 'heart_disease', 'epilepsy'
];

const VALID_SYMPTOMS = [
  'chest_pain', 'difficulty_breathing', 'shortness_of_breath', 'severe_bleeding',
  'unconscious', 'stroke_symptoms', 'high_fever', 'persistent_vomiting',
  'severe_pain', 'confusion', 'fainting', 'rapid_heartbeat', 'fever', 'cough',
  'headache', 'nausea', 'dizziness', 'fatigue', 'back_pain', 'joint_pain',
  'abdominal_pain', 'muscle_weakness', 'swelling', 'rash',
];

const PATIENT_TABS = [
  { key: 'dashboard', path: '/patient' },
  { key: 'report', path: '/patient/report' },
  { key: 'clinicians', path: '/patient/clinicians' },
  { key: 'history', path: '/patient/history' },
  { key: 'profile', path: '/patient/profile' },
];
const PATIENT_PATH_TO_TAB = Object.fromEntries(PATIENT_TABS.map(t => [t.path, t.key]));

export default function PatientDashboard() {
  const { user } = useAuth();
  const { success, error: toastError } = useToast();
  const { setUnreadAlerts } = useNotifications();
  const location = useLocation();
  const navigate = useNavigate();
  const [patient, setPatient] = useState(null);
  const [reports, setReports] = useState([]);
  const [assignments, setAssignments] = useState([]);
  const [loading, setLoading] = useState(true);
  const activeTab = PATIENT_PATH_TO_TAB[location.pathname] || 'dashboard';
  const [showReportModal, setShowReportModal] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [reportForm, setReportForm] = useState({
    symptoms: [], severity: 'MILD', durationDays: 1, frequency: 'FIRST_TIME',
    notes: '', temperature: '', heartRate: '', medicationAdherent: null,
  });
  const [savingProfile, setSavingProfile] = useState(false);
  const [profileForm, setProfileForm] = useState({
    phone: '',
    emergencyContact: '',
    address: '',
    chronicConditions: [],
    allergies: '',
    baselineStatus: 'stable'
  });

  const handleTabChange = (tabKey) => {
    const tabPath = tabKey === 'dashboard' ? '/patient' : `/patient/${tabKey}`;
    navigate(tabPath, { replace: true });
  };

  useEffect(() => {
    loadData();
  }, []);

  async function loadData() {
    setLoading(true);
    try {
      let patientsData = [];
      let allAssignments = [];
      try {
        patientsData = await patientsAPI.getAll();
      } catch (err) {
        toastError('Failed to load patients: ' + (err.message || 'Unknown error'));
      }
      try {
        allAssignments = await assignmentsAPI.getAll();
      } catch (err) {
        toastError('Failed to load assignments: ' + (err.message || 'Unknown error'));
      }

      const myPatient = patientsData.find(p => p.userId === user.id);
      setPatient(myPatient);

      if (myPatient) {
        let chronic = [];
        try { chronic = myPatient.chronicConditions ? JSON.parse(myPatient.chronicConditions) : []; } catch(e){}
        let algs = [];
        try { algs = myPatient.allergies ? JSON.parse(myPatient.allergies) : []; } catch(e){}
        
        setProfileForm({
          phone: myPatient.user?.phone || '',
          emergencyContact: myPatient.emergencyContact || '',
          address: myPatient.address || '',
          chronicConditions: chronic,
          allergies: algs.join(', '),
          baselineStatus: myPatient.baselineStatus || 'stable'
        });

        try {
          const myReports = await symptomReportsAPI.getByPatient(myPatient.id);
          setReports(myReports);
        } catch (err) {
          toastError('Failed to load reports: ' + (err.message || 'Unknown error'));
        }
        const myAssignments = allAssignments.filter(a => a.patientId === myPatient.id && a.status === 'ACTIVE');
        setAssignments(myAssignments);
      }
    } catch (err) {
      toastError('Failed to load patient data: ' + (err.message || 'Unknown error'));
    } finally {
      setLoading(false);
    }
  }

  const toggleSymptom = (symptom) => {
    setReportForm(f => ({
      ...f,
      symptoms: f.symptoms.includes(symptom)
        ? f.symptoms.filter(s => s !== symptom)
        : [...f.symptoms, symptom],
    }));
  };

  const handleSubmitReport = async (e) => {
    e.preventDefault();
    if (!patient || reportForm.symptoms.length === 0) return;
    setSubmitting(true);
    try {
      const payload = {
        patientId: patient.id,
        symptoms: reportForm.symptoms,
        severity: reportForm.severity,
        durationDays: parseInt(reportForm.durationDays),
        frequency: reportForm.frequency,
        notes: reportForm.notes || null,
        temperature: reportForm.temperature ? parseFloat(reportForm.temperature) : null,
        heartRate: reportForm.heartRate ? parseInt(reportForm.heartRate) : null,
        medicationAdherent: reportForm.medicationAdherent,
      };
      await symptomReportsAPI.create(payload);
      setShowReportModal(false);
      setReportForm({
        symptoms: [], severity: 'MILD', durationDays: 1, frequency: 'FIRST_TIME',
        notes: '', temperature: '', heartRate: '', medicationAdherent: null,
      });
      success('Symptom report submitted successfully');
      loadData();
    } catch (err) {
      toastError('Failed to submit report: ' + (err.message || 'Unknown error'));
    } finally {
      setSubmitting(false);
    }
  };

  const handleSaveProfile = async (e) => {
    e.preventDefault();
    if (!patient) return;
    setSavingProfile(true);
    try {
      await Promise.all([
        patientsAPI.update(patient.id, {
          emergencyContact: profileForm.emergencyContact,
          address: profileForm.address,
          chronicConditions: profileForm.chronicConditions,
          allergies: profileForm.allergies.split(',').map(a => a.trim()).filter(a => a),
          baselineStatus: profileForm.baselineStatus
        }),
        usersAPI.update(user.id, { phone: profileForm.phone || null }),
      ]);
      success('Profile updated successfully');
      loadData();
    } catch (err) {
      toastError('Failed to update profile: ' + (err.message || 'Unknown error'));
    } finally {
      setSavingProfile(false);
    }
  };

  const handleConditionToggle = (condition) => {
    setProfileForm(f => ({
      ...f,
      chronicConditions: f.chronicConditions.includes(condition)
        ? f.chronicConditions.filter(c => c !== condition)
        : [...f.chronicConditions, condition]
    }));
  };

  const formatSymptom = (s) => s.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());

  const chartData = [...reports]
    .sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt))
    .slice(-10)
    .map(r => ({
      date: new Date(r.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
      riskScore: r.riskScore,
      severity: r.severity === 'CRITICAL' ? 4 : r.severity === 'SEVERE' ? 3 : r.severity === 'MODERATE' ? 2 : 1,
    }));

  if (loading) {
    return (
      <>
        <TopBar title="My Health Dashboard" subtitle="Personal health overview" />
        <div className="page-content flex-center" style={{ height: '60vh' }}>
          <LoadingSpinner />
        </div>
      </>
    );
  }

  return (
    <>
      <TopBar title="My Health Dashboard" subtitle={`Welcome back, ${user?.fullName || 'Patient'}`} />
      <div className="page-content">
        {/* Tab Navigation */}
        <div className="tabs" style={{ marginBottom: 20 }}>
          <button className={`tab ${activeTab === 'dashboard' ? 'active' : ''}`} onClick={() => handleTabChange('dashboard')}>
            <LayoutDashboard size={15} style={{ marginRight: 6, verticalAlign: 'middle' }} /> Dashboard
          </button>
          <button className={`tab ${activeTab === 'report' ? 'active' : ''}`} onClick={() => handleTabChange('report')}>
            <FileHeart size={15} style={{ marginRight: 6, verticalAlign: 'middle' }} /> Report Symptoms
          </button>
          <button className={`tab ${activeTab === 'clinicians' ? 'active' : ''}`} onClick={() => handleTabChange('clinicians')}>
            <Stethoscope size={15} style={{ marginRight: 6, verticalAlign: 'middle' }} /> My Clinicians
          </button>
          <button className={`tab ${activeTab === 'history' ? 'active' : ''}`} onClick={() => handleTabChange('history')}>
            <ClipboardList size={15} style={{ marginRight: 6, verticalAlign: 'middle' }} /> My Reports
          </button>
          <button className={`tab ${activeTab === 'profile' ? 'active' : ''}`} onClick={() => handleTabChange('profile')}>
            <UserCircle size={15} style={{ marginRight: 6, verticalAlign: 'middle' }} /> Profile
          </button>
        </div>

        {/* Dashboard Tab */}
        {activeTab === 'dashboard' && (<>
        {/* Stats Grid */}
        <div className="stats-grid stagger-children">
          <StatCard
            icon={Shield}
            label="Risk Level"
            value={patient?.currentRiskLevel || 'LOW'}
            color={patient?.currentRiskLevel === 'HIGH' ? 'red' : patient?.currentRiskLevel === 'MEDIUM' ? 'amber' : 'green'}
            delay={0}
          />
          <StatCard
            icon={Activity}
            label="Trend Status"
            value={patient?.currentTrendStatus || 'STABLE'}
            color={patient?.currentTrendStatus === 'WORSENING' ? 'red' : patient?.currentTrendStatus === 'IMPROVING' ? 'green' : 'blue'}
            delay={80}
          />
          <StatCard
            icon={ClipboardList}
            label="Total Reports"
            value={reports.length}
            color="teal"
            delay={160}
          />
          <StatCard
            icon={Stethoscope}
            label="Active Clinicians"
            value={assignments.length}
            color="blue"
            delay={240}
          />
        </div>

        {/* Charts + Timeline */}
        <div className="patient-grid mt-24">
          {/* Risk Score Chart */}
          <div className="card" style={{ padding: 24 }}>
            <h3 className="section-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <Activity size={18} style={{ color: 'var(--color-teal)' }} /> Risk Score Trend
            </h3>
            {chartData.length > 1 ? (
              <ResponsiveContainer width="100%" height={250}>
                <AreaChart data={chartData}>
                  <defs>
                    <linearGradient id="riskGrad" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor="var(--color-teal)" stopOpacity={0.3} />
                      <stop offset="100%" stopColor="var(--color-teal)" stopOpacity={0.02} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border-light)" />
                  <XAxis dataKey="date" fontSize={12} stroke="var(--color-text-muted)" />
                  <YAxis fontSize={12} stroke="var(--color-text-muted)" />
                  <Tooltip
                    contentStyle={{
                      background: 'var(--color-surface)', border: '1px solid var(--color-border)',
                      borderRadius: 10, fontSize: '0.82rem', boxShadow: 'var(--shadow-md)'
                    }}
                  />
                  <Area type="monotone" dataKey="riskScore" stroke="var(--color-teal)" fill="url(#riskGrad)" strokeWidth={2.5} dot={{ r: 4, fill: 'var(--color-teal)' }} />
                </AreaChart>
              </ResponsiveContainer>
            ) : (
              <div className="empty-state"><p>Not enough data for chart yet</p></div>
            )}
          </div>

          {/* My Clinicians */}
          <div className="card" style={{ padding: 24 }}>
            <h3 className="section-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <Stethoscope size={18} style={{ color: 'var(--color-blue)' }} /> My Clinicians
            </h3>
            {assignments.length > 0 ? (
              <div className="clinician-list">
                {assignments.map((a, idx) => {
                  const clinicianName = a.clinician?.fullName || a.clinician?.user?.fullname || a.clinician?.user?.email || `Clinician #${a.clinicianId}`;
                  return (
                  <div key={a.id} className="clinician-card animate-fade-in" style={{ animationDelay: `${idx * 80}ms` }}>
                    <div className="clinician-avatar">{clinicianName[0]?.toUpperCase()}</div>
                    <div className="clinician-info">
                      <span className="clinician-name">{clinicianName}</span>
                      <span className="clinician-context">{a.clinician?.specialization?.replace(/_/g, ' ')} · {a.careContext?.replace(/_/g, ' ')}</span>
                      {a.reason && <span className="clinician-reason">{a.reason}</span>}
                    </div>
                    <span className="badge badge-success">Active</span>
                  </div>
                  );
                })}
              </div>
            ) : (
              <div className="empty-state">
                <Stethoscope size={32} className="empty-state-icon" />
                <p>No clinicians assigned yet</p>
              </div>
            )}
          </div>
        </div>

        {/* Recent Reports */}
        <div className="card mt-24" style={{ padding: 24 }}>
          <h3 className="section-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <FileHeart size={18} style={{ color: 'var(--color-teal)' }} /> Recent Reports
          </h3>
          {reports.length > 0 ? (
            <div className="reports-list">
              {reports.slice(0, 5).map((r, idx) => {
                let symptoms = [];
                try { symptoms = JSON.parse(r.symptoms); } catch {}
                return (
                  <div key={r.id} className="report-row animate-fade-in" style={{ animationDelay: `${idx * 50}ms` }}>
                    <div className="report-date">
                      <Calendar size={14} />
                      {new Date(r.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                    </div>
                    <div className="report-symptoms">
                      {symptoms.slice(0, 3).map(s => (
                        <span key={s} className="badge badge-neutral">{formatSymptom(s)}</span>
                      ))}
                      {symptoms.length > 3 && <span className="badge badge-neutral">+{symptoms.length - 3}</span>}
                    </div>
                    <span className={`badge ${r.severity === 'CRITICAL' || r.severity === 'SEVERE' ? 'badge-danger' : r.severity === 'MODERATE' ? 'badge-warning' : 'badge-success'}`}>
                      {r.severity}
                    </span>
                    <RiskBadge level={r.riskLevel} />
                    <span className="report-score">Score: {r.riskScore?.toFixed(1)}</span>
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="empty-state">
              <FileHeart size={32} className="empty-state-icon" />
              <p>No reports submitted yet</p>
            </div>
          )}
        </div>
        </>)}

        {/* Report Symptoms Tab */}
        {activeTab === 'report' && (
          <div className="card" style={{ padding: 24 }}>
            <h3 className="section-title" style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 20 }}>
              <Plus size={18} style={{ color: 'var(--color-teal)' }} /> Report New Symptoms
            </h3>
            <form onSubmit={handleSubmitReport} className="report-form">
              <div className="form-group">
                <label className="form-label">Symptoms (select all that apply)</label>
                <div className="symptom-grid">
                  {VALID_SYMPTOMS.map(s => (
                    <button
                      key={s} type="button"
                      className={`symptom-chip ${reportForm.symptoms.includes(s) ? 'symptom-chip--active' : ''}`}
                      onClick={() => toggleSymptom(s)}
                    >
                      {formatSymptom(s)}
                    </button>
                  ))}
                </div>
                {reportForm.symptoms.length === 0 && (
                  <span style={{ fontSize: '0.75rem', color: 'var(--color-danger)' }}>
                    <AlertCircle size={12} style={{ verticalAlign: 'middle', marginRight: 4 }} />
                    Select at least one symptom
                  </span>
                )}
              </div>
              <div className="report-form-row">
                <div className="form-group">
                  <label className="form-label">Severity</label>
                  <select className="form-select" value={reportForm.severity} onChange={e => setReportForm(f => ({ ...f, severity: e.target.value }))}>
                    <option value="MILD">Mild</option>
                    <option value="MODERATE">Moderate</option>
                    <option value="SEVERE">Severe</option>
                    <option value="CRITICAL">Critical</option>
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label">Duration (days)</label>
                  <input type="number" className="form-input" min="1" value={reportForm.durationDays} onChange={e => setReportForm(f => ({ ...f, durationDays: e.target.value }))} />
                </div>
                <div className="form-group">
                  <label className="form-label">Frequency</label>
                  <select className="form-select" value={reportForm.frequency} onChange={e => setReportForm(f => ({ ...f, frequency: e.target.value }))}>
                    <option value="FIRST_TIME">First Time</option>
                    <option value="RECURRING">Recurring</option>
                    <option value="CHRONIC">Chronic</option>
                  </select>
                </div>
              </div>
              <div className="report-form-row">
                <div className="form-group">
                  <label className="form-label"><Thermometer size={13} /> Temperature (\u00b0C)</label>
                  <input type="number" step="0.1" className="form-input" placeholder="e.g. 37.5" value={reportForm.temperature} onChange={e => setReportForm(f => ({ ...f, temperature: e.target.value }))} />
                </div>
                <div className="form-group">
                  <label className="form-label"><HeartPulse size={13} /> Heart Rate (bpm)</label>
                  <input type="number" className="form-input" placeholder="e.g. 80" value={reportForm.heartRate} onChange={e => setReportForm(f => ({ ...f, heartRate: e.target.value }))} />
                </div>
                <div className="form-group">
                  <label className="form-label"><Pill size={13} /> Medication Adherent</label>
                  <select className="form-select" value={reportForm.medicationAdherent === null ? '' : reportForm.medicationAdherent} onChange={e => setReportForm(f => ({ ...f, medicationAdherent: e.target.value === '' ? null : e.target.value === 'true' }))}>
                    <option value="">Not applicable</option>
                    <option value="true">Yes</option>
                    <option value="false">No</option>
                  </select>
                </div>
              </div>
              <div className="form-group">
                <label className="form-label">Notes (optional)</label>
                <textarea className="form-input" rows="3" placeholder="Describe how you're feeling..." value={reportForm.notes} onChange={e => setReportForm(f => ({ ...f, notes: e.target.value }))} />
              </div>
              <button type="submit" className="btn btn-primary" disabled={submitting || reportForm.symptoms.length === 0} style={{ width: '100%', marginTop: 8 }}>
                {submitting ? 'Submitting...' : <><Send size={16} /> Submit Report</>}
              </button>
            </form>
          </div>
        )}

        {/* My Clinicians Tab */}
        {activeTab === 'clinicians' && (
          <div className="card" style={{ padding: 24 }}>
            <h3 className="section-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <Stethoscope size={18} style={{ color: 'var(--color-blue)' }} /> My Clinicians
            </h3>
            {assignments.length > 0 ? (
              <div className="clinician-list">
                {assignments.map((a, idx) => {
                  const clinicianName = a.clinician?.fullName || a.clinician?.user?.fullname || a.clinician?.user?.email || `Clinician #${a.clinicianId}`;
                  return (
                  <div key={a.id} className="clinician-card animate-fade-in" style={{ animationDelay: `${idx * 80}ms` }}>
                    <div className="clinician-avatar">{clinicianName[0]?.toUpperCase()}</div>
                    <div className="clinician-info">
                      <span className="clinician-name">{clinicianName}</span>
                      <span className="clinician-context">{a.clinician?.specialization?.replace(/_/g, ' ')} · {a.careContext?.replace(/_/g, ' ')}</span>
                      {a.reason && <span className="clinician-reason">{a.reason}</span>}
                    </div>
                    <span className="badge badge-success">Active</span>
                  </div>
                  );
                })}
              </div>
            ) : (
              <div className="empty-state">
                <Stethoscope size={36} className="empty-state-icon" />
                <p>No clinicians assigned yet</p>
              </div>
            )}
          </div>
        )}

        {/* My Reports Tab */}
        {activeTab === 'history' && (
          <div className="card" style={{ padding: 24 }}>
            <h3 className="section-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <ClipboardList size={18} style={{ color: 'var(--color-teal)' }} /> My Reports
            </h3>
            {reports.length > 0 ? (
              <div className="reports-list">
                {reports.map((r, idx) => {
                  let symptoms = [];
                  try { symptoms = JSON.parse(r.symptoms); } catch {}
                  return (
                    <div key={r.id} className="report-row animate-fade-in" style={{ animationDelay: `${idx * 50}ms` }}>
                      <div className="report-date">
                        <Calendar size={14} />
                        {new Date(r.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                      </div>
                      <div className="report-symptoms">
                        {symptoms.slice(0, 3).map(s => (
                          <span key={s} className="badge badge-neutral">{formatSymptom(s)}</span>
                        ))}
                        {symptoms.length > 3 && <span className="badge badge-neutral">+{symptoms.length - 3}</span>}
                      </div>
                      <span className={`badge ${r.severity === 'CRITICAL' || r.severity === 'SEVERE' ? 'badge-danger' : r.severity === 'MODERATE' ? 'badge-warning' : 'badge-success'}`}>
                        {r.severity}
                      </span>
                      <RiskBadge level={r.riskLevel} />
                      <span className="report-score">Score: {r.riskScore?.toFixed(1)}</span>
                    </div>
                  );
                })}
              </div>
            ) : (
              <div className="empty-state">
                <ClipboardList size={36} className="empty-state-icon" />
                <p>No reports submitted yet</p>
              </div>
            )}
          </div>
        )}

        {/* Profile Tab */}
        {activeTab === 'profile' && (
          <div className="card" style={{ padding: 24 }}>
            <h3 className="section-title" style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 20 }}>
              <UserCircle size={18} style={{ color: 'var(--color-teal)' }} /> Clinical Profile
            </h3>
            <form onSubmit={handleSaveProfile} className="report-form">
              
              <div className="report-form-row">
                <div className="form-group">
                  <label className="form-label">Phone Number</label>
                  <input type="tel" className="form-input" placeholder="e.g. +263-77-000-0000" value={profileForm.phone} onChange={e => setProfileForm(f => ({ ...f, phone: e.target.value }))} />
                </div>
                <div className="form-group">
                  <label className="form-label">Emergency Contact</label>
                  <input type="text" className="form-input" value={profileForm.emergencyContact} onChange={e => setProfileForm(f => ({ ...f, emergencyContact: e.target.value }))} required />
                </div>
              </div>

              <div className="report-form-row">
                <div className="form-group">
                  <label className="form-label">Address</label>
                  <input type="text" className="form-input" value={profileForm.address} onChange={e => setProfileForm(f => ({ ...f, address: e.target.value }))} />
                </div>
              </div>

              <div className="form-group">
                <label className="form-label">Baseline Status</label>
                <select className="form-select" value={profileForm.baselineStatus} onChange={e => setProfileForm(f => ({ ...f, baselineStatus: e.target.value }))}>
                  <option value="stable">Stable</option>
                  <option value="fragile">Fragile</option>
                  <option value="unknown">Unknown</option>
                </select>
              </div>

              <div className="form-group">
                <label className="form-label">Chronic Conditions</label>
                <div className="symptom-grid">
                  {COMMON_CONDITIONS.map(c => (
                    <button
                      key={c} type="button"
                      className={`symptom-chip ${profileForm.chronicConditions.includes(c) ? 'symptom-chip--active' : ''}`}
                      onClick={() => handleConditionToggle(c)}
                    >
                      {formatSymptom(c)}
                    </button>
                  ))}
                </div>
              </div>

              <div className="form-group">
                <label className="form-label">Allergies (comma-separated)</label>
                <input type="text" className="form-input" placeholder="e.g. penicillin, peanuts" value={profileForm.allergies} onChange={e => setProfileForm(f => ({ ...f, allergies: e.target.value }))} />
              </div>

              <button type="submit" className="btn btn-primary" disabled={savingProfile} style={{ width: '100%', marginTop: 8 }}>
                {savingProfile ? 'Saving...' : 'Save Profile'}
              </button>
            </form>
          </div>
        )}
      </div>
    </>
  );
}
